version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - .:/app
      - ./media:/app/media
    ports:
      - "8001:8001"
    depends_on:
      - postgres
    restart: on-failure

  postgres:
    image: postgres:latest
    restart: always
    env_file:
      - .env

    volumes:
      - "./postgres:/var/lib/postgresql/data"
volumes:
  media:
