# Generated by Django 5.0.6 on 2024-06-11 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('icon', models.ImageField(upload_to='advantages/', verbose_name='Иконка')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Преимущество',
                'verbose_name_plural': 'Преимущества',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('short_description', models.TextField(verbose_name='Мини описание')),
                ('image', models.ImageField(upload_to='categories/', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('profession', models.CharField(max_length=255, verbose_name='Профессия')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('short_description', models.TextField(verbose_name='Мини описание')),
                ('description', models.TextField(verbose_name='Описание')),
                ('main_image', models.ImageField(upload_to='news/', verbose_name='Главное изображение')),
                ('author', models.CharField(max_length=255, verbose_name='Автор')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('work_scope', models.CharField(max_length=255, verbose_name='Объем работ')),
                ('secondary_description', models.TextField(blank=True, null=True, verbose_name='Второе описание')),
                ('client', models.CharField(max_length=255, verbose_name='Клиент')),
                ('dimensions', models.CharField(blank=True, max_length=255, null=True, verbose_name='Размеры')),
                ('location', models.CharField(max_length=255, verbose_name='Локация')),
                ('type', models.CharField(max_length=255, verbose_name='Тип')),
                ('image1', models.ImageField(upload_to='projects/', verbose_name='Изображение 1')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='Изображение 2')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='Изображение 3')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='Изображение 4')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Второе название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('secondary_description', models.TextField(blank=True, null=True, verbose_name='Второе описание')),
                ('image1', models.ImageField(upload_to='services/', verbose_name='Изображение 1')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='Изображение 2')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='Изображение 3')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('profession', models.CharField(max_length=255, verbose_name='Профессия')),
                ('description', models.TextField(verbose_name='Описание')),
                ('photo', models.ImageField(upload_to='testimonials/', verbose_name='Фотография')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
