# Generated by Django 5.0.6 on 2024-06-11 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_sitesetting_rename_description_news_richtextfield_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='hours',
            field=models.CharField(default=1, max_length=123, verbose_name='Рабочие часы'),
            preserve_default=False,
        ),
    ]
