# Generated by Django 5.0.6 on 2024-06-11 02:58

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_sitesetting_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='RichTextField',
        ),
        migrations.AddField(
            model_name='news',
            name='description',
            field=ckeditor.fields.RichTextField(default=1, verbose_name='Описание'),
            preserve_default=False,
        ),
    ]
