# Generated by Django 5.0.6 on 2024-06-11 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_industry_product_applicaton'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Applicaton',
            new_name='Application',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='main.category'),
            preserve_default=False,
        ),
    ]
