# Generated by Django 5.0.6 on 2024-06-17 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_product_image_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='image',
            field=models.ImageField(default=1, upload_to='images/', verbose_name='Картинка'),
            preserve_default=False,
        ),
    ]
