# Generated by Django 5.0.6 on 2024-06-18 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_advantage_counter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advantage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Преимущество', 'verbose_name_plural': 'Преимущества'},
        ),
    ]
