# Generated by Django 5.0.6 on 2024-06-18 05:15

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_advantage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='advantage',
            name='title_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='advantage',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='banner',
            name='description_ky',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='banner',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='banner',
            name='title_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='banner',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='category',
            name='short_description_ky',
            field=models.TextField(null=True, verbose_name='Мини описание'),
        ),
        migrations.AddField(
            model_name='category',
            name='short_description_ru',
            field=models.TextField(null=True, verbose_name='Мини описание'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='employee',
            name='profession_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Профессия'),
        ),
        migrations.AddField(
            model_name='employee',
            name='profession_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Профессия'),
        ),
        migrations.AddField(
            model_name='news',
            name='description_ky',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='news',
            name='description_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='news',
            name='short_description_ky',
            field=models.TextField(null=True, verbose_name='Мини описание'),
        ),
        migrations.AddField(
            model_name='news',
            name='short_description_ru',
            field=models.TextField(null=True, verbose_name='Мини описание'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ky',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_ky',
            field=models.CharField(max_length=123, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_ru',
            field=models.CharField(max_length=123, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='project',
            name='description_ky',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='project',
            name='description_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='project',
            name='secondary_description_ky',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Второе описание'),
        ),
        migrations.AddField(
            model_name='project',
            name='secondary_description_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Второе описание'),
        ),
        migrations.AddField(
            model_name='project',
            name='title_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='project',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_ky',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='service',
            name='secondary_description_ky',
            field=models.TextField(blank=True, null=True, verbose_name='Второе описание'),
        ),
        migrations.AddField(
            model_name='service',
            name='secondary_description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Второе описание'),
        ),
        migrations.AddField(
            model_name='service',
            name='subtitle_ky',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Второе название'),
        ),
        migrations.AddField(
            model_name='service',
            name='subtitle_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Второе название'),
        ),
        migrations.AddField(
            model_name='service',
            name='title_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='service',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='description_ky',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='О нас'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='description_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='О нас'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='description_ky',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='name_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='profession_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Профессия'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='profession_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Профессия'),
        ),
    ]
