# Generated by Django 5.0.6 on 2024-06-18 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_categoryvacancy_title_ky_categoryvacancy_title_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='mini_description',
            field=models.CharField(default=1, max_length=123, verbose_name='мини название'),
            preserve_default=False,
        ),
    ]
