# Generated by Django 5.0.6 on 2024-06-19 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_vacancy_mini_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='industry',
            name='title_ky',
            field=models.CharField(max_length=123, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='industry',
            name='title_ru',
            field=models.CharField(max_length=123, null=True, verbose_name='Название'),
        ),
    ]
