# Generated by Django 5.0.6 on 2024-06-19 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_sitesetting_director_sitesetting_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='title',
            field=models.CharField(blank=True, max_length=123, null=True, verbose_name='Название компании'),
        ),
    ]
