# Generated by Django 5.0.6 on 2024-06-19 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_sitesetting_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='photo_video',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Название компании'),
        ),
    ]
