# Generated by Django 5.0.6 on 2024-06-19 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_sitesetting_photo_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.product', verbose_name='Почта'),
        ),
    ]
