# Generated by Django 5.0.6 on 2024-06-19 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_application_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_text', models.TextField(help_text='Оригинальный текст, который отображается на сайте.', max_length=20000, verbose_name='Оригинальный текст')),
                ('current_text', models.TextField(help_text='Измененный или текущий текст, который отображается на сайте.', max_length=20000, verbose_name='Текущий текст')),
                ('current_text_ru', models.TextField(help_text='Измененный или текущий текст, который отображается на сайте.', max_length=20000, null=True, verbose_name='Текущий текст')),
                ('current_text_ky', models.TextField(help_text='Измененный или текущий текст, который отображается на сайте.', max_length=20000, null=True, verbose_name='Текущий текст')),
            ],
            options={
                'verbose_name': 'Контент сайта',
                'verbose_name_plural': 'Контент сайта',
            },
        ),
        migrations.AlterField(
            model_name='application',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.product', verbose_name='Товар'),
        ),
    ]
