# Generated by Django 5.1.1 on 2024-09-18 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0023_sitecontent_alter_application_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=123)),
                ("image", models.ImageField(upload_to="images/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Изображение о нас",
            },
        ),
        migrations.AlterField(
            model_name="sitesetting",
            name="director",
            field=models.CharField(max_length=123, verbose_name="Генеральный директор"),
        ),
    ]
